#!/bin/bash
# print eve or odd

#i=1
#while [ $i -le 10 ]
#do 
#  echo $i
#  (( i++ ))
#done

for b in {1..10}
do
  if (( $b % 2 == 1 ))
  then
    echo " $b is odd " 
  else
    echo " $b is even "
  fi
done
  
